import React from 'react'

const availableCourses = [
    {
        campus: ' ',
        crn: '12119',
        code: 'COMP337',
        name: 'DESIGN AND ANALYSIS OF ALGORITHMS',
        letter: 'D4',
        credits: '3',
        type: 'Lecture',
        days: 'Wednesday',
        times: '1201 - 1400',
        bldg: ' ',
        class: ' ',
        dr: 'Ziad Fouad Doughan',
        capacity: '14',
        otherMajor: ' ',
        major: 'Include:, Computer Engineering',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
      {
        campus: ' ',
        crn: '12119',
        code: 'COMP337',
        name: 'DESIGN AND ANALYSIS OF ALGORITHMS',
        letter: 'D4',
        credits: '3',
        type: 'Lab',
        days: 'Wednesday',
        times: '1401 - 1600',
        bldg: ' ',
        class: ' ',
        dr: 'Mohamad Ahmad Maad',
        capacity: '14',
        otherMajor: ' ',
        major: 'Include:, Computer Engineering',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '10465',
        code: 'COMP361',
        name: 'CONTROL SYSTEMS FOR COMPUTER ENGINEERS',
        letter: 'D1',
        credits: '3',
        type: 'Lab',
        days: 'Monday',
        times: '1201 - 1400',
        bldg: 'ENG',
        class: 'TBA',
        dr: 'Mohamad Omar Ibrahim',
        capacity: '4',
        otherMajor: 'Include:, Engineering',
        major: 'Include:, Computer Engineering, Electric Power & Machines Eng.',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '10465',
        code: 'COMP361',
        name: 'CONTROL SYSTEMS FOR COMPUTER ENGINEERS',
        letter: 'D1',
        credits: '3',
        type: 'Lecture',
        days: 'Monday',
        times: '0801 - 1000',
        bldg: 'ENG',
        class: 'EG141',
        dr: 'Mohammad Houssein Ayache',
        capacity: '4',
        otherMajor: 'Include:, Engineering',
        major: 'Include:, Computer Engineering, Electric Power & Machines Eng.',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '10465',
        code: 'COMP361',
        name: 'CONTROL SYSTEMS FOR COMPUTER ENGINEERS',
        letter: 'D1',
        credits: '3',
        type: 'Lab',
        days: 'Monday',
        times: '1201 - 1400',
        bldg: 'ENG',
        class: 'TBA',
        dr: 'Mohammad Mouwaffak Al Sayed',
        capacity: '4',
        otherMajor: 'Include:, Engineering',
        major: 'Include:, Computer Engineering, Electric Power & Machines Eng.',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '12178',
        code: 'COMP361',
        name: 'CONTROL SYSTEMS FOR COMPUTER ENGINEERS',
        letter: 'D2',
        credits: '3',
        type: 'Lecture',
        days: 'Monday',
        times: '0801 - 1000',
        bldg: 'ENG',
        class: 'EG141',
        dr: 'Mohammad Houssein Ayache',
        capacity: '4',
        otherMajor: 'Include:, Engineering',
        major: 'Include:, Computer Engineering, Electric Power & Machines Eng.',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '12178',
        code: 'COMP361',
        name: 'CONTROL SYSTEMS FOR COMPUTER ENGINEERS',
        letter: 'D2',
        credits: '3',
        type: 'Lab',
        days: 'Friday',
        times: '0801 - 1000',
        bldg: 'ENG',
        class: 'TBA',
        dr: 'Mohamad Omar Ibrahim',
        capacity: '4',
        otherMajor: 'Include:, Engineering',
        major: 'Include:, Computer Engineering, Electric Power & Machines Eng.',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '10467',
        code: 'COMP361',
        name: 'CONTROL SYSTEMS FOR COMPUTER ENGINEERS',
        letter: 'D3',
        credits: '3',
        type: 'Lab',
        days: 'Wednesday',
        times: '1401 - 1600',
        bldg: 'ENG',
        class: 'TBA',
        dr: 'Mohammad Mouwaffak Al Sayed',
        capacity: '7',
        otherMajor: 'Include:, Engineering',
        major: 'Include:, Computer Engineering, Electric Power & Machines Eng.',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '10467',
        code: 'COMP361',
        name: 'CONTROL SYSTEMS FOR COMPUTER ENGINEERS',
        letter: 'D3',
        credits: '3',
        type: 'Lab',
        days: 'Wednesday',
        times: '1401 - 1600',
        bldg: 'ENG',
        class: 'TBA',
        dr: 'Mohamad Omar Ibrahim',
        capacity: '7',
        otherMajor: 'Include:, Engineering',
        major: 'Include:, Computer Engineering, Electric Power & Machines Eng.',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '10467',
        code: 'COMP361',
        name: 'CONTROL SYSTEMS FOR COMPUTER ENGINEERS',
        letter: 'D3',
        credits: '3',
        type: 'Lecture',
        days: 'Monday',
        times: '0801 - 1000',
        bldg: 'ENG',
        class: 'EG141',
        dr: 'Mohammad Houssein Ayache',
        capacity: '7',
        otherMajor: 'Include:, Engineering',
        major: 'Include:, Computer Engineering, Electric Power & Machines Eng.',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '10469',
        code: 'COMP361',
        name: 'CONTROL SYSTEMS FOR COMPUTER ENGINEERS',
        letter: 'D5',
        credits: '3',
        type: 'Lab',
        days: 'Tuesday',
        times: '1001 - 1200',
        bldg: 'ENG',
        class: 'TBA',
        dr: 'Mohammad Mouwaffak Al Sayed',
        capacity: 'Closed',
        otherMajor: 'Include:, Engineering',
        major: 'Include:, Computer Engineering, Electric Power & Machines Eng.',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '10469',
        code: 'COMP361',
        name: 'CONTROL SYSTEMS FOR COMPUTER ENGINEERS',
        letter: 'D5',
        credits: '3',
        type: 'Lab',
        days: 'Tuesday',
        times: '1001 - 1200',
        bldg: 'ENG',
        class: 'TBA',
        dr: 'Mohamad Omar Ibrahim',
        capacity: 'Closed',
        otherMajor: 'Include:, Engineering',
        major: 'Include:, Computer Engineering, Electric Power & Machines Eng.',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '10469',
        code: 'COMP361',
        name: 'CONTROL SYSTEMS FOR COMPUTER ENGINEERS',
        letter: 'D5',
        credits: '3',
        type: 'Lecture',
        days: 'Monday',
        times: '0801 - 1000',
        bldg: 'ENG',
        class: 'EG141',
        dr: 'Mohammad Houssein Ayache',
        capacity: 'Closed',
        otherMajor: 'Include:, Engineering',
        major: 'Include:, Computer Engineering, Electric Power & Machines Eng.',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '10470',
        code: 'COMP423',
        name: 'COMPUTER ARCHITECTURE',
        letter: 'D1',
        credits: '3',
        type: 'Lecture',
        days: 'Tuesday',
        times: '0801 - 1000',
        bldg: 'ENG',
        class: 'EB132-1',
        dr: 'Ali Masoud Haidar',
        capacity: '2',
        otherMajor: ' ',
        major: 'Include:, Computer Engineering',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '10470',
        code: 'COMP423',
        name: 'COMPUTER ARCHITECTURE',
        letter: 'D1',
        credits: '3',
        type: 'Lab',
        days: 'Tuesday',
        times: '1201 - 1400',
        bldg: 'ENG',
        class: 'computer lab C',
        dr: 'Rabee Aladdine Kiblawi',
        capacity: '2',
        otherMajor: ' ',
        major: 'Include:, Computer Engineering',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '10471',
        code: 'COMP423',
        name: 'COMPUTER ARCHITECTURE',
        letter: 'D2',
        credits: '3',
        type: 'Lab',
        days: 'Tuesday',
        times: '1401 - 1600',
        bldg: 'ENG',
        class: 'computer lab C',
        dr: 'Rabee Aladdine Kiblawi',
        capacity: '8',
        otherMajor: ' ',
        major: 'Include:, Computer Engineering',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '10471',
        code: 'COMP423',
        name: 'COMPUTER ARCHITECTURE',
        letter: 'D2',
        credits: '3',
        type: 'Lecture',
        days: 'Tuesday',
        times: '0801 - 1000',
        bldg: 'ENG',
        class: 'EB132-1',
        dr: 'Ali Masoud Haidar',
        capacity: '8',
        otherMajor: ' ',
        major: 'Include:, Computer Engineering',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '10472',
        code: 'COMP423',
        name: 'COMPUTER ARCHITECTURE',
        letter: 'D3',
        credits: '3',
        type: 'Lab',
        days: 'Thursday',
        times: '0801 - 1000',
        bldg: 'ENG',
        class: 'computer lab C',
        dr: 'Rabee Aladdine Kiblawi',
        capacity: '4',
        otherMajor: ' ',
        major: 'Include:, Computer Engineering',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '10472',
        code: 'COMP423',
        name: 'COMPUTER ARCHITECTURE',
        letter: 'D3',
        credits: '3',
        type: 'Lecture',
        days: 'Tuesday',
        times: '0801 - 1000',
        bldg: 'ENG',
        class: 'EB132-1',
        dr: 'Ali Masoud Haidar',
        capacity: '4',
        otherMajor: ' ',
        major: 'Include:, Computer Engineering',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '10473',
        code: 'COMP453',
        name: 'Transmission and Processing of Digital Signals',
        letter: 'D1',
        credits: '3',
        type: 'Lecture',
        days: 'Monday',
        times: '1401 - 1600',
        bldg: 'ENG',
        class: 'EB132-1',
        dr: 'Imane Mahmoud Haidar',
        capacity: '5',
        otherMajor: 'Include:, Engineering',
        major: 'Include:, Computer Engineering',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '10473',
        code: 'COMP453',
        name: 'Transmission and Processing of Digital Signals',
        letter: 'D1',
        credits: '3',
        type: 'Lab',
        days: 'Thursday',
        times: '0801 - 1000',
        bldg: 'ENG',
        class: 'computer lab D',
        dr: 'Lara Malek Fawaz',
        capacity: '5',
        otherMajor: 'Include:, Engineering',
        major: 'Include:, Computer Engineering',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '10474',
        code: 'COMP453',
        name: 'Transmission and Processing of Digital Signals',
        letter: 'D2',
        credits: '3',
        type: 'Lecture',
        days: 'Monday',
        times: '1401 - 1600',
        bldg: 'ENG',
        class: 'EB132-1',
        dr: 'Imane Mahmoud Haidar',
        capacity: 'Closed',
        otherMajor: 'Include:, Engineering',
        major: 'Include:, Computer Engineering',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '10474',
        code: 'COMP453',
        name: 'Transmission and Processing of Digital Signals',
        letter: 'D2',
        credits: '3',
        type: 'Lab',
        days: 'Thursday',
        times: '1001 - 1200',
        bldg: 'ENG',
        class: 'computer lab D',
        dr: 'Lara Malek Fawaz',
        capacity: 'Closed',
        otherMajor: 'Include:, Engineering',
        major: 'Include:, Computer Engineering',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '10475',
        code: 'COMP453',
        name: 'Transmission and Processing of Digital Signals',
        letter: 'D3',
        credits: '3',
        type: 'Lecture',
        days: 'Monday',
        times: '1401 - 1600',
        bldg: 'ENG',
        class: 'EB132-1',
        dr: 'Imane Mahmoud Haidar',
        capacity: '10',
        otherMajor: 'Include:, Engineering',
        major: 'Include:, Computer Engineering',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '10475',
        code: 'COMP453',
        name: 'Transmission and Processing of Digital Signals',
        letter: 'D3',
        credits: '3',
        type: 'Lab',
        days: 'Thursday',
        times: '1401 - 1600',
        bldg: 'ENG',
        class: 'computer Lab B',
        dr: 'Lara Malek Fawaz',
        capacity: '10',
        otherMajor: 'Include:, Engineering',
        major: 'Include:, Computer Engineering',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '12083',
        code: 'COMP554',
        name: 'IOT PLATFORM DESIGN AND IMPLEMENTATION',
        letter: 'D1',
        credits: '3',
        type: 'Lecture',
        days: 'Wednesday',
        times: '1201 - 1400',
        bldg: 'ENG',
        class: 'EB132-1',
        dr: 'Walid Ali Fahs',
        capacity: '7',
        otherMajor: ' ',
        major: 'Include:, Computer Engineering',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '12083',
        code: 'COMP554',
        name: 'IOT PLATFORM DESIGN AND IMPLEMENTATION',
        letter: 'D1',
        credits: '3',
        type: 'Lab',
        days: 'Wednesday',
        times: '1001 - 1200',
        bldg: 'ENG',
        class: 'computer Lab B',
        dr: 'TBA TBA',
        capacity: '7',
        otherMajor: ' ',
        major: 'Include:, Computer Engineering',
        courseType: 'Major'
      },
      {
        campus: 'Beirut',
        crn: '12134',
        code: 'COMP499',
        name: 'Internship',
        letter: '1',
        credits: '1',
        type: 'Lecture',
        days: 'Friday',
        times: '1001 - 1100',
        bldg: 'TBA',
        class: ' ',
        dr: 'Ziad Fouad Doughan',
        capacity: '39',
        otherMajor: 'Include:, Engineering',
        major: ' ',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '10478',
        code: 'COMP499',
        name: 'Internship',
        letter: 'D1',
        credits: '1',
        type: 'Lecture',
        days: 'Friday',
        times: '1401 - 1500',
        bldg: 'ENG',
        class: 'TBA',
        dr: 'Imane Mahmoud Haidar',
        capacity: '7',
        otherMajor: 'Include:, Engineering',
        major: ' ',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '10479',
        code: 'COMP500',
        name: 'RESEARCH METHODOLOGY',
        letter: 'D1',
        credits: '2',
        type: 'Lecture',
        days: 'Thursday',
        times: '1401 - 1600',
        bldg: 'ENG',
        class: 'EB132-1',
        dr: 'Mohammad Houssein Ayache',
        capacity: '29',
        otherMajor: ' ',
        major: 'Include:, Computer Engineering',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '10480',
        code: 'COMP501',
        name: 'Final Year Project I',
        letter: 'D1',
        credits: '1',
        type: 'Lecture',
        days: 'Friday',
        times: '1001 - 1100',
        bldg: 'ENG',
        class: 'TBA',
        dr: 'Ali Masoud Haidar',
        capacity: '19',
        otherMajor: 'Include:, Engineering',
        major: 'Include:, Computer Engineering',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '10481',
        code: 'COMP501',
        name: 'Final Year Project I',
        letter: 'D2',
        credits: '1',
        type: 'Lecture',
        days: 'Friday',
        times: '1001 - 1100',
        bldg: 'ENG',
        class: 'TBA',
        dr: 'Ziad Fouad Doughan',
        capacity: '8',
        otherMajor: 'Include:, Engineering',
        major: 'Include:, Computer Engineering',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '10482',
        code: 'COMP501',
        name: 'Final Year Project I',
        letter: 'D3',
        credits: '1',
        type: 'Lecture',
        days: 'Friday',
        times: '1001 - 1100',
        bldg: 'ENG',
        class: 'TBA',
        dr: 'Imane Mahmoud Haidar',
        capacity: '13',
        otherMajor: 'Include:, Engineering',
        major: 'Include:, Computer Engineering',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '10483',
        code: 'COMP501',
        name: 'Final Year Project I',
        letter: 'D4',
        credits: '1',
        type: 'Lecture',
        days: 'Friday',
        times: '1001 - 1100',
        bldg: 'ENG',
        class: 'TBA',
        dr: 'Hiba Sami Bazzi',
        capacity: '18',
        otherMajor: 'Include:, Engineering',
        major: 'Include:, Computer Engineering',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '10484',
        code: 'COMP502',
        name: 'final year project II',
        letter: 'D1',
        credits: '3',
        type: 'Lecture',
        days: 'Friday',
        times: '1001 - 1300',
        bldg: 'ENG',
        class: 'TBA',
        dr: 'Ali Masoud Haidar',
        capacity: '19',
        otherMajor: ' ',
        major: 'Include:, Computer Engineering',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '10485',
        code: 'COMP502',
        name: 'final year project II',
        letter: 'D2',
        credits: '3',
        type: 'Lecture',
        days: 'Friday',
        times: '1001 - 1300',
        bldg: 'ENG',
        class: 'TBA',
        dr: 'Ziad Fouad Doughan',
        capacity: '15',
        otherMajor: ' ',
        major: 'Include:, Computer Engineering',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '10486',
        code: 'COMP502',
        name: 'final year project II',
        letter: 'D3',
        credits: '3',
        type: 'Lecture',
        days: 'Friday',
        times: '1001 - 1300',
        bldg: 'ENG',
        class: 'TBA',
        dr: 'Imane Mahmoud Haidar',
        capacity: '13',
        otherMajor: ' ',
        major: 'Include:, Computer Engineering',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '10487',
        code: 'COMP502',
        name: 'final year project II',
        letter: 'D4',
        credits: '3',
        type: 'Lecture',
        days: 'Friday',
        times: '1001 - 1300',
        bldg: 'ENG',
        class: 'TBA',
        dr: 'Hiba Sami Bazzi',
        capacity: '17',
        otherMajor: ' ',
        major: 'Include:, Computer Engineering',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '10490',
        code: 'COMP543',
        name: 'CRYPTOGRAPHY AND INFORMATION SECURITY',
        letter: 'D1',
        credits: '3',
        type: 'Lecture',
        days: 'Monday',
        times: '1201 - 1400',
        bldg: 'ENG',
        class: 'EB132-1',
        dr: 'Imane Mahmoud Haidar',
        capacity: '2',
        otherMajor: ' ',
        major: 'Include:, Computer Engineering',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '10490',
        code: 'COMP543',
        name: 'CRYPTOGRAPHY AND INFORMATION SECURITY',
        letter: 'D1',
        credits: '3',
        type: 'Lecture',
        days: 'Tuesday',
        times: '1301 - 1400',
        bldg: 'ENG',
        class: 'EB132-1',
        dr: 'Imane Mahmoud Haidar',
        capacity: '2',
        otherMajor: ' ',
        major: 'Include:, Computer Engineering',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '10493',
        code: 'COMP543L',
        name: 'CRYPTOGRAPHY AND INFORMATION SECURITY LAB',
        letter: 'D1',
        credits: '1',
        type: 'Lab',
        days: 'Monday',
        times: '1401 - 1600',
        bldg: 'ENG',
        class: 'Computer Lab E',
        dr: 'Ali Hassan Nassar',
        capacity: 'Closed',
        otherMajor: ' ',
        major: 'Include:, Computer Engineering',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '10494',
        code: 'COMP543L',
        name: 'CRYPTOGRAPHY AND INFORMATION SECURITY LAB',
        letter: 'D2',
        credits: '1',
        type: 'Lab',
        days: 'Wednesday',
        times: '0801 - 1000',
        bldg: 'ENG',
        class: 'computer lab D',
        dr: 'Ali Hassan Nassar',
        capacity: '3',
        otherMajor: ' ',
        major: 'Include:, Computer Engineering',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '10462',
        code: 'COMP337',
        name: 'DESIGN AND ANALYSIS OF ALGORITHMS',
        letter: 'D1',
        credits: '3',
        type: 'Lecture',
        days: 'Wednesday',
        times: '1201 - 1400',
        bldg: 'ENG',
        class: 'EG141',
        dr: 'Ziad Fouad Doughan',
        capacity: 'Closed',
        otherMajor: ' ',
        major: 'Include:, Computer Engineering',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '10462',
        code: 'COMP337',
        name: 'DESIGN AND ANALYSIS OF ALGORITHMS',
        letter: 'D1',
        credits: '3',
        type: 'Lab',
        days: 'Monday',
        times: '1201 - 1400',
        bldg: 'ENG',
        class: 'Computer Lab E',
        dr: 'Mohamad Ahmad Maad',
        capacity: 'Closed',
        otherMajor: ' ',
        major: 'Include:, Computer Engineering',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '10463',
        code: 'COMP337',
        name: 'DESIGN AND ANALYSIS OF ALGORITHMS',
        letter: 'D2',
        credits: '3',
        type: 'Lecture',
        days: 'Wednesday',
        times: '1201 - 1400',
        bldg: 'ENG',
        class: 'EG141',
        dr: 'Ziad Fouad Doughan',
        capacity: '8',
        otherMajor: ' ',
        major: 'Include:, Computer Engineering',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
      {
        campus: 'Debbieh',
        crn: '10463',
        code: 'COMP337',
        name: 'DESIGN AND ANALYSIS OF ALGORITHMS',
        letter: 'D2',
        credits: '3',
        type: 'Lab',
        days: 'Tuesday',
        times: '1201 - 1400',
        bldg: 'ENG',
        class: 'Computer Lab E',
        dr: 'Mohamad Ahmad Maad',
        capacity: '8',
        otherMajor: ' ',
        major: 'Include:, Computer Engineering',
        emptySpace1: ' ',
        emptySpace2: ' ',
        emptySpace3: ' ',
        emptySpace4: ' ',
        courseType: 'Major'
      },
  ];
  
  const takenCourses = [
    {
      Term: "Spring 2022 / 2023",
      Course: "COMP452",
      Title: "compilers",
      Credits: 3,
      Level: "UG",
      Grade: "A",
      SGPA: 3.55,
    },
    {
      Term: "Spring 2022 / 2023",
      Course: "COMP500",
      Title: "research methodology",
      Credits: 2,
      Level: "UG",
      Grade: "B",
      SGPA: 3.55,
    },
    {
      Term: "Spring 2022 / 2023",
      Course: "WRNL200",
      Title: "Work Ready Now",
      Credits: 3,
      Level: "UG",
      Grade: "B+",
      SGPA: 3.55,
    },
    {
      Term: "Spring 2022 / 2023",
      Course: "COMP443",
      Title: "operating systems",
      Credits: 3,
      Level: "UG",
      Grade: "A",
      SGPA: 3.55,
    },
    {
      Term: "Spring 2022 / 2023",
      Course: "CHEM405",
      Title: "Solid State Chemistry",
      Credits: 2,
      Level: "UG",
      Grade: "B-",
      SGPA: 3.55,
    },
    {
      Term: "Spring 2022 / 2023",
      Course: "COMP525",
      Title: "embedded & microprocessor syst",
      Credits: 3,
      Level: "UG",
      Grade: "A-",
      SGPA: 3.55,
    },
    {
      Term: "Spring 2022 / 2023",
      Course: "COMP501",
      Title: "Final Year Project I",
      Credits: 1,
      Level: "UG",
      Grade: "A",
      SGPA: 3.55,
    },
    {
      Term: "Fall 2022 / 2023",
      Course: "COMP453",
      Title: "transm. & proc. of dig. signal",
      Credits: 3,
      Level: "UG",
      Grade: "B",
      SGPA: 3.37,
    },
    {
      Term: "Fall 2022 / 2023",
      Course: "COMP512",
      Title: "web programming",
      Credits: 3,
      Level: "UG",
      Grade: "A+",
      SGPA: 3.37,
    },
    {
      Term: "Fall 2022 / 2023",
      Course: "COMP543",
      Title: "cryptography & info. security",
      Credits: 3,
      Level: "UG",
      Grade: "B-",
      SGPA: 3.37,
    },
    {
      Term: "Fall 2022 / 2023",
      Course: "COMP560",
      Title: "Deep Learning",
      Credits: 3,
      Level: "UG",
      Grade: "A-",
      SGPA: 3.37,
    },
    {
      Term: "Fall 2022 / 2023",
      Course: "COMP543L",
      Title: "crypto. & info. security lab",
      Credits: 1,
      Level: "UG",
      Grade: "B",
      SGPA: 3.37,
    },
    {
      Term: "Fall 2022 / 2023",
      Course: "COME411",
      Title: "instrumrntation",
      Credits: 3,
      Level: "UG",
      Grade: "B",
      SGPA: 3.37,
    },
    {
      Term: "Fall 2022 / 2023",
      Course: "COMP474",
      Title: "Introduction to Robotics",
      Credits: 3,
      Level: "UG",
      Grade: "A",
      SGPA: 3.37,
    },
    {
      Term: "Spring 2021 / 2022",
      Course: "COMP454",
      Title: "computer networks",
      Credits: 3,
      Level: "UG",
      Grade: "B+",
      SGPA: 3.64,
    },
    {
      Term: "Spring 2021 / 2022",
      Course: "ENVI004",
      Title: "Envi. Issues in Lebanon",
      Credits: 2,
      Level: "UG",
      Grade: "A",
      SGPA: 3.64,
    },
    {
      Term: "Spring 2021 / 2022",
      Course: "CVLE007",
      Title: "Traffic Safety",
      Credits: 1,
      Level: "UG",
      Grade: "A-",
      SGPA: 3.64,
    },
    {
      Term: "Spring 2021 / 2022",
      Course: "MGMT002",
      Title: "Entrepreneurship",
      Credits: 2,
      Level: "UG",
      Grade: "B-",
      SGPA: 3.64,
    },
    {
      Term: "Spring 2021 / 2022",
      Course: "COMP454L",
      Title: "computer networks lab",
      Credits: 1,
      Level: "UG",
      Grade: "C+",
      SGPA: 3.64,
    },
    {
      Term: "Spring 2021 / 2022",
      Course: "COMP344",
      Title: "database systems",
      Credits: 3,
      Level: "UG",
      Grade: "A-",
      SGPA: 3.64,
    },
    {
      Term: "Spring 2021 / 2022",
      Course: "COMP364",
      Title: "intro. to AI & ML",
      Credits: 3,
      Level: "UG",
      Grade: "A",
      SGPA: 3.64,
    },
    {
      Term: "Spring 2021 / 2022",
      Course: "COMP428",
      Title: "digital systems design",
      Credits: 3,
      Level: "UG",
      Grade: "A",
      SGPA: 3.64,
    },
    {
      Term: "Spring 2021 / 2022",
      Course: "COMP442",
      Title: "software engineering",
      Credits: 3,
      Level: "UG",
      Grade: "A",
      SGPA: 3.64,
    },
    {
      Term: "Fall 2021 / 2022",
      Course: "IC003",
      Title: "Intern&Comput.Core Cert",
      Credits: 0,
      Level: "UG",
      Grade: "P",
      SGPA: 3.26,
    },
    {
      Term: "Fall 2021 / 2022",
      Course: "CMPS005",
      Title: "BULDING BASIC ANDROID APPS",
      Credits: 2,
      Level: "UG",
      Grade: "A-",
      SGPA: 3.26,
    },
    {
      Term: "Fall 2021 / 2022",
      Course: "COMP477",
      Title: "emerging trends in comp eng",
      Credits: 3,
      Level: "UG",
      Grade: "C",
      SGPA: 3.26,
    },
    {
      Term: "Fall 2021 / 2022",
      Course: "COMP423",
      Title: "computer architecture",
      Credits: 3,
      Level: "UG",
      Grade: "C",
      SGPA: 3.26,
    },
    {
      Term: "Fall 2021 / 2022",
      Course: "COMP361",
      Title: "control systems for comp eng",
      Credits: 3,
      Level: "UG",
      Grade: "A",
      SGPA: 3.26,
    },
    // {
    //   Term: "Fall 2021 / 2022",
    //   Course: "COMP337",
    //   Title: "design & analysis of algorithm",
    //   Credits: 3,
    //   Level: "UG",
    //   Grade: "A",
    //   SGPA: 3.26,
    // },
    {
      Term: "Fall 2021 / 2022",
      Course: "COME223",
      Title: "digital electornics",
      Credits: 3,
      Level: "UG",
      Grade: "A",
      SGPA: 3.26,
    },
    {
      Term: "Spring 2020 / 2021",
      Course: "BLAW001",
      Title: "Human Rights",
      Credits: 1,
      Level: "UG",
      Grade: "A",
      SGPA: 2.95,
    },
    {
      Term: "Spring 2020 / 2021",
      Course: "COMP232",
      Title: "data structures",
      Credits: 3,
      Level: "UG",
      Grade: "B-",
      SGPA: 2.95,
    },
    {
      Term: "Spring 2020 / 2021",
      Course: "MATH381",
      Title: "Probability And Statistics",
      Credits: 3,
      Level: "UG",
      Grade: "D",
      SGPA: 2.95,
    },
    {
      Term: "Spring 2020 / 2021",
      Course: "COMP311",
      Title: "object oriented prg.",
      Credits: 3,
      Level: "UG",
      Grade: "A-",
      SGPA: 2.95,
    },
    {
      Term: "Spring 2020 / 2021",
      Course: "COMP325",
      Title: "microprocessor org. &design",
      Credits: 3,
      Level: "UG",
      Grade: "B",
      SGPA: 2.95,
    },
    {
      Term: "Spring 2020 / 2021",
      Course: "ARAB001",
      Title: "Arabic language & Literature",
      Credits: 2,
      Level: "UG",
      Grade: "A+",
      SGPA: 2.95,
    },
    {
      Term: "Spring 2020 / 2021",
      Course: "INME221",
      Title: "Engineering Economy",
      Credits: 3,
      Level: "UG",
      Grade: "B",
      SGPA: 2.95,
    },
    {
      Term: "Fall 2020 / 2021",
      Course: "POWE212",
      Title: "electric circuits 1",
      Credits: 3,
      Level: "UG",
      Grade: "A-",
      SGPA: 3.41,
    },
    {
      Term: "Fall 2020 / 2021",
      Course: "COMP210",
      Title: "PROGRAMMING II",
      Credits: 3,
      Level: "UG",
      Grade: "B+",
      SGPA: 3.41,
    },
    {
      Term: "Fall 2020 / 2021",
      Course: "COMP215",
      Title: "Programming for eng.",
      Credits: 3,
      Level: "UG",
      Grade: "A",
      SGPA: 3.41,
    },
    {
      Term: "Fall 2020 / 2021",
      Course: "COMP231",
      Title: "discrete structures",
      Credits: 3,
      Level: "UG",
      Grade: "A+",
      SGPA: 3.41,
    },
    {
      Term: "Fall 2020 / 2021",
      Course: "COMP226",
      Title: "digital systems 2",
      Credits: 3,
      Level: "UG",
      Grade: "B",
      SGPA: 3.41,
    },
    {
      Term: "Fall 2020 / 2021",
      Course: "ENGL300",
      Title: "Speech Communications",
      Credits: 2,
      Level: "UG",
      Grade: "C",
      SGPA: 3.41,
    },
    {
      Term: "Spring 2019 / 2020",
      Course: "PHYS282",
      Title: "Material Properties and Heat",
      Credits: 3,
      Level: "UG",
      Grade: "A",
      SGPA: 4,
    },
    {
      Term: "Spring 2019 / 2020",
      Course: "ENGL211",
      Title: "Advanced Writing",
      Credits: 2,
      Level: "UG",
      Grade: "P",
      SGPA: 4,
    },
    {
      Term: "Spring 2019 / 2020",
      Course: "COMP208",
      Title: "Programming I",
      Credits: 3,
      Level: "UG",
      Grade: "A",
      SGPA: 4,
    },
    {
      Term: "Spring 2019 / 2020",
      Course: "COMP225",
      Title: "digital systems 1",
      Credits: 3,
      Level: "UG",
      Grade: "P",
      SGPA: 4,
    },
    {
      Term: "Spring 2019 / 2020",
      Course: "CHEM241",
      Title: "Principles of Chemistry",
      Credits: 3,
      Level: "UG",
      Grade: "P",
      SGPA: 4,
    },
    {
      Term: "Spring 2019 / 2020",
      Course: "MATH283",
      Title: "Differential Equations",
      Credits: 3,
      Level: "UG",
      Grade: "P",
      SGPA: 4,
    },
    {
      Term: "Fall 2019 / 2020",
      Course: "ENGL001",
      Title: "General English",
      Credits: 2,
      Level: "UG",
      Grade: "B+",
      SGPA: 3.67,
    },
    {
      Term: "Fall 2019 / 2020",
      Course: "ENGR002",
      Title: "intro. to engineering",
      Credits: 2,
      Level: "UG",
      Grade: "C",
      SGPA: 3.67,
    },
    {
      Term: "Fall 2019 / 2020",
      Course: "MATH281",
      Title: "Linear Algebra",
      Credits: 3,
      Level: "UG",
      Grade: "A+",
      SGPA: 3.67,
    },
    {
      Term: "Fall 2019 / 2020",
      Course: "MATH282",
      Title: "Calculus",
      Credits: 3,
      Level: "UG",
      Grade: "A",
      SGPA: 3.67,
    },
    {
      Term: "Fall 2019 / 2020",
      Course: "MCHE213",
      Title: "Dynamics",
      Credits: 3,
      Level: "UG",
      Grade: "A",
      SGPA: 3.67,
    },
    {
      Term: "Fall 2019 / 2020",
      Course: "PHYS281",
      Title: "Electricity and Magnetism",
      Credits: 3,
      Level: "UG",
      Grade: "A+",
      SGPA: 3.67,
    },
    {
      Term: "Lebanese baccalaureate or Eqv.",
      Course: "BIOL120",
      Title: "Introduction to Biology",
      Credits: 3,
      Level: "UG",
      Grade: "TR",
      SGPA: 0,
    },
    {
      Term: "Lebanese baccalaureate or Eqv.",
      Course: "BIOL121",
      Title: "General Biology I",
      Credits: 3,
      Level: "UG",
      Grade: "TR",
      SGPA: 0,
    },
    {
      Term: "Lebanese baccalaureate or Eqv.",
      Course: "PHIL110",
      Title: "Introduction to Philosophy",
      Credits: 3,
      Level: "UG",
      Grade: "TR",
      SGPA: 0,
    },
    {
      Term: "Lebanese baccalaureate or Eqv.",
      Course: "ENGL110",
      Title: "Freshman English I",
      Credits: 3,
      Level: "UG",
      Grade: "TR",
      SGPA: 0,
    },
    {
      Term: "Lebanese baccalaureate or Eqv.",
      Course: "MATH110",
      Title: "Intr.Calc.&Analyt.Geom.I",
      Credits: 3,
      Level: "UG",
      Grade: "TR",
      SGPA: 0,
    },
    {
      Term: "Lebanese baccalaureate or Eqv.",
      Course: "ARAB110",
      Title: "Introd.to Arabic Literature",
      Credits: 3,
      Level: "UG",
      Grade: "TR",
      SGPA: 0,
    },
    {
      Term: "Lebanese baccalaureate or Eqv.",
      Course: "PHYS110",
      Title: "Introduction to Physics I",
      Credits: 3,
      Level: "UG",
      Grade: "TR",
      SGPA: 0,
    },
    {
      Term: "Lebanese baccalaureate or Eqv.",
      Course: "CHEM110",
      Title: "Introduction to Chemistry I",
      Credits: 3,
      Level: "UG",
      Grade: "TR",
      SGPA: 0,
    },
    {
      Term: "Lebanese baccalaureate or Eqv.",
      Course: "HIST110",
      Title: "History of Modern Lebanon",
      Credits: 3,
      Level: "UG",
      Grade: "TR",
      SGPA: 0,
    },
    {
      Term: "Lebanese baccalaureate or Eqv.",
      Course: "MATH111",
      Title: "Intr.Calc.&Analyt.Geom.||",
      Credits: 3,
      Level: "UG",
      Grade: "TR",
      SGPA: 0,
    },
  ];
  
  const allCourses = [
    {
        "Course": "COMP499",
        "Title": "Internship",
        "Credits": 1,
        "Level": "UG",
        "Type": "CE Core"
    },
    {
        "Course": "COMP502",
        "Title": "Final Year Project II",
        "Credits": 3,
        "Level": "UG",
        "Type": "CE Core"
    },
    {
        "Course": "COMP452",
        "Title": "compilers",
        "Credits": 3,
        "Level": "UG",
        "Type": "CE Core"
    },
    {
        "Course": "COMP500",
        "Title": "research methodology",
        "Credits": 2,
        "Level": "UG",
        "Type": "CE Core"
    },
    {
        "Course": "COMP443",
        "Title": "operating systems",
        "Credits": 3,
        "Level": "UG",
        "Type": "CE Core"
    },
    {
        "Course": "COMP525",
        "Title": "embedded & microprocessor syst",
        "Credits": 3,
        "Level": "UG",
        "Type": "CE Core"
    },
    {
        "Course": "COMP501",
        "Title": "Final Year Project I",
        "Credits": 1,
        "Level": "UG",
        "Type": "CE Core"
    },
    {
        "Course": "COMP453",
        "Title": "transm. & proc. of dig. signal",
        "Credits": 3,
        "Level": "UG",
        "Type": "CE Core"
    },
    {
        "Course": "COMP512",
        "Title": "web programming",
        "Credits": 3,
        "Level": "UG",
        "Type": "CE Core"
    },
    {
        "Course": "COMP543",
        "Title": "cryptography & info. security",
        "Credits": 3,
        "Level": "UG",
        "Type": "CE Core"
    },
    {
        "Course": "COMP560",
        "Title": "Deep Learning",
        "Credits": 3,
        "Level": "UG",
        "Type": "CE Core"
    },
    {
        "Course": "COMP543L",
        "Title": "crypto. & info. security lab",
        "Credits": 1,
        "Level": "UG",
        "Type": "CE Core"
    },
    {
        "Course": "COMP474",
        "Title": "Introduction to Robotics",
        "Credits": 3,
        "Level": "UG",
        "Type": "CE Core"
    },
    {
        "Course": "COMP454",
        "Title": "computer networks",
        "Credits": 3,
        "Level": "UG",
        "Type": "CE Core"
    },
    {
        "Course": "COMP454L",
        "Title": "computer networks lab",
        "Credits": 1,
        "Level": "UG",
        "Type": "CE Core"
    },
    {
        "Course": "COMP344",
        "Title": "database systems",
        "Credits": 3,
        "Level": "UG",
        "Type": "CE Core"
    },
    {
        "Course": "COMP364",
        "Title": "intro. to AI & ML",
        "Credits": 3,
        "Level": "UG",
        "Type": "CE Core"
    },
    {
        "Course": "COMP428",
        "Title": "digital systems design",
        "Credits": 3,
        "Level": "UG",
        "Type": "CE Core"
    },
    {
        "Course": "COMP442",
        "Title": "software engineering",
        "Credits": 3,
        "Level": "UG",
        "Type": "CE Core"
    },
    {
        "Course": "COMP477",
        "Title": "emerging trends in comp eng",
        "Credits": 3,
        "Level": "UG",
        "Type": "CE Core"
    },
    {
        "Course": "COMP423",
        "Title": "computer architecture",
        "Credits": 3,
        "Level": "UG",
        "Type": "CE Core"
    },
    {
        "Course": "COMP361",
        "Title": "control systems for comp eng",
        "Credits": 3,
        "Level": "UG",
        "Type": "CE Core"
    },
    {
        "Course": "COMP337",
        "Title": "design & analysis of algorithm",
        "Credits": 3,
        "Level": "UG",
        "Type": "CE Core"
    },
    {
        "Course": "COME223",
        "Title": "digital electornics",
        "Credits": 3,
        "Level": "UG",
        "Type": "CE Core"
    },
    {
        "Course": "COMP232",
        "Title": "data structures",
        "Credits": 3,
        "Level": "UG",
        "Type": "CE Core"
    },
    {
        "Course": "COMP311",
        "Title": "object oriented prg.",
        "Credits": 3,
        "Level": "UG",
        "Type": "CE Core"
    },
    {
        "Course": "COMP325",
        "Title": "microprocessor org. &design",
        "Credits": 3,
        "Level": "UG",
        "Type": "CE Core"
    },
    {
        "Course": "COMP210",
        "Title": "PROGRAMMING II",
        "Credits": 3,
        "Level": "UG",
        "Type": "CE Core"
    },
    {
        "Course": "COMP215",
        "Title": "Programming for eng.",
        "Credits": 3,
        "Level": "UG",
        "Type": "CE Core"
    },
    {
        "Course": "COMP231",
        "Title": "discrete structures",
        "Credits": 3,
        "Level": "UG",
        "Type": "CE Core"
    },
    {
        "Course": "COMP226",
        "Title": "digital systems 2",
        "Credits": 3,
        "Level": "UG",
        "Type": "CE Core"
    },
    {
        "Course": "COMP208",
        "Title": "Programming I",
        "Credits": 3,
        "Level": "UG",
        "Type": "CE Core"
    },
    {
        "Course": "COMP225",
        "Title": "digital systems 1",
        "Credits": 3,
        "Level": "UG",
        "Type": "CE Core"
    },
    {
        "Course": "WRNL200",
        "Title": "Work Ready Now",
        "Credits": 3,
        "Level": "UG",
        "Type": "General Elective"
    },
    {
        "Course": "ENVI004",
        "Title": "Envi. Issues in Lebanon",
        "Credits": 2,
        "Level": "UG",
        "Type": "General Elective"
    },
    {
        "Course": "CVLE007",
        "Title": "Traffic Safety",
        "Credits": 1,
        "Level": "UG",
        "Type": "General Elective"
    },
    {
        "Course": "CMPS005",
        "Title": "BULDING BASIC ANDROID APPS",
        "Credits": 2,
        "Level": "UG",
        "Type": "General Elective"
    },
    {
        "Course": "BLAW001",
        "Title": "Human Rights",
        "Credits": 1,
        "Level": "UG",
        "Type": "GNR"
    },
    {
        "Course": "ENGR001",
        "Title": "Engineering Ethics",
        "Credits": 1,
        "Level": "UG",
        "Type": "GNR"
    },
    {
        "Course": "MATH284",
        "Title": "Numerical Analysis",
        "Credits": 3,
        "Level": "UG",
        "Type": "GNR"
    },
    {
        "Course": "CHEM405",
        "Title": "Solid State Chemistry",
        "Credits": 2,
        "Level": "UG",
        "Type": "GNR"
    },
    {
        "Course": "COME411",
        "Title": "instrumrntation",
        "Credits": 3,
        "Level": "UG",
        "Type": "GNR"
    },
    {
        "Course": "MGMT002",
        "Title": "Entrepreneurship",
        "Credits": 2,
        "Level": "UG",
        "Type": "GNR"
    },
    {
        "Course": "MATH381",
        "Title": "Probability And Statistics",
        "Credits": 3,
        "Level": "UG",
        "Type": "GNR"
    },
    {
        "Course": "ARAB001",
        "Title": "Arabic language & Literature",
        "Credits": 2,
        "Level": "UG",
        "Type": "GNR"
    },
    {
        "Course": "INME221",
        "Title": "Engineering Economy",
        "Credits": 3,
        "Level": "UG",
        "Type": "GNR"
    },
    {
        "Course": "POWE212",
        "Title": "electric circuits 1",
        "Credits": 3,
        "Level": "UG",
        "Type": "GNR"
    },
    {
        "Course": "ENGL300",
        "Title": "Speech Communications",
        "Credits": 2,
        "Level": "UG",
        "Type": "GNR"
    },
    {
        "Course": "PHYS282",
        "Title": "Material Properties and Heat",
        "Credits": 3,
        "Level": "UG",
        "Type": "GNR"
    },
    {
        "Course": "ENGL211",
        "Title": "Advanced Writing",
        "Credits": 2,
        "Level": "UG",
        "Type": "GNR"
    },
    {
        "Course": "CHEM241",
        "Title": "Principles of Chemistry",
        "Credits": 3,
        "Level": "UG",
        "Type": "GNR"
    },
    {
        "Course": "MATH283",
        "Title": "Differential Equations",
        "Credits": 3,
        "Level": "UG",
        "Type": "GNR"
    },
    {
        "Course": "ENGL001",
        "Title": "General English",
        "Credits": 2,
        "Level": "UG",
        "Type": "GNR"
    },
    {
        "Course": "ENGR002",
        "Title": "intro. to engineering",
        "Credits": 2,
        "Level": "UG",
        "Type": "GNR"
    },
    {
        "Course": "MATH281",
        "Title": "Linear Algebra",
        "Credits": 3,
        "Level": "UG",
        "Type": "GNR"
    },
    {
        "Course": "MATH282",
        "Title": "Calculus",
        "Credits": 3,
        "Level": "UG",
        "Type": "GNR"
    },
    {
        "Course": "MCHE213",
        "Title": "Dynamics",
        "Credits": 3,
        "Level": "UG",
        "Type": "GNR"
    },
    {
        "Course": "PHYS281",
        "Title": "Electricity and Magnetism",
        "Credits": 3,
        "Level": "UG",
        "Type": "GNR"
    },
    {
        "Course": "IC003",
        "Title": "Intern&Comput.Core Cert",
        "Credits": 0,
        "Level": "UG",
        "Type": "Certificate"
    }
  ]
  
  function remaincourses(availableCourses, takenCourses, allCourses) {
    const takenCourseCodes = takenCourses.map(course => course.Course);
  
    const remainingCourses = allCourses
      .filter(course => !takenCourseCodes.includes(course.Course))
      .flatMap(course => {
        const matchingAvailableCourses = availableCourses.filter(
          availableCourse => availableCourse.code === course.Course
        );
  
        if (matchingAvailableCourses.length > 0) {
          return matchingAvailableCourses.map(matchingAvailableCourse => ({
            campus: matchingAvailableCourse.campus,
            crn: matchingAvailableCourse.crn,
            code: matchingAvailableCourse.code,
            name: matchingAvailableCourse.name,
            letter: matchingAvailableCourse.letter,
            credits: matchingAvailableCourse.credits,
            type: matchingAvailableCourse.type,
            days: matchingAvailableCourse.days,
            times: matchingAvailableCourse.times,
            bldg: matchingAvailableCourse.bldg,
            class: matchingAvailableCourse.class,
            dr: matchingAvailableCourse.dr,
            capacity: matchingAvailableCourse.capacity,
            otherMajor: matchingAvailableCourse.otherMajor,
            major: matchingAvailableCourse.major,
            emptySpace1: matchingAvailableCourse.emptySpace1,
            emptySpace2: matchingAvailableCourse.emptySpace2,
            emptySpace3: matchingAvailableCourse.emptySpace3,
            emptySpace4: matchingAvailableCourse.emptySpace4,
            courseType: matchingAvailableCourse.courseType,
          }));
        }
  
        return null;
      })
      .filter(course => course !== null);
  
    return remainingCourses;
  } 

async function page() {

    // try {
    //     const res = await fetch("http://localhost:3000/api/courseOffering", {
    //       cache: "no-store",
    //     });
    
    //     if (!res.ok) {
    //       throw new Error("Failed!");
    //     }
    //     const data = await res.json();
    //    console.log(data)
    //   } catch (error) {
    //     console.error("Error fetching data:", error);
    //     throw error;
    //   }

      // Example usage
      const remainingCourses = remaincourses(availableCourses, takenCourses, allCourses);
      console.log("remainingCourses");
      console.log(remainingCourses);
      
      
  return (
    <div>REM C</div>
  )
}

export default page